-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-01-14 16:09:13 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE je_na (
    mec_idme      INTEGER NOT NULL,
    mec_idzl      INTEGER NOT NULL,
    prijava_idk   INTEGER NOT NULL,
    prijava_idkat INTEGER NOT NULL
);

ALTER TABLE je_na
    ADD CONSTRAINT je_na_pk PRIMARY KEY ( mec_idme,
                                          mec_idzl,
                                          prijava_idk,
                                          prijava_idkat );

CREATE TABLE kategorija (
    idkat            INTEGER NOT NULL,
    nazkat           VARCHAR2(60) NOT NULL,
    tezkat           NUMBER NOT NULL,
    iskkat           VARCHAR2(30) NOT NULL,
    takmicenje_idtak INTEGER NOT NULL
);

ALTER TABLE kategorija ADD CONSTRAINT kategorija_pk PRIMARY KEY ( idkat );

CREATE TABLE klub (
    idkl       INTEGER NOT NULL,
    nazkl      VARCHAR2(60) NOT NULL,
    borkl      VARCHAR2(60) NOT NULL,
    trener_idk INTEGER NOT NULL
);

CREATE UNIQUE INDEX klub__idx ON
    klub (
        trener_idk
    ASC );

ALTER TABLE klub ADD CONSTRAINT klub_pk PRIMARY KEY ( idkl );

CREATE TABLE korisnik (
    idk    INTEGER NOT NULL,
    imek   VARCHAR2(20) NOT NULL,
    nazk   VARCHAR2(20) NOT NULL,
    sifrk  VARCHAR2(64) NOT NULL,
    brtelk INTEGER,
    email  VARCHAR2(30) NOT NULL,
    tipk   VARCHAR2(50) NOT NULL
);

ALTER TABLE korisnik
    ADD CONSTRAINT ch_inh_korisnik CHECK ( tipk IN ( 'Organizator', 'Sudija', 'Takmicar', 'Trener' ) );

ALTER TABLE korisnik ADD CONSTRAINT korisnik_pk PRIMARY KEY ( idk );

CREATE TABLE mec (
    idme      INTEGER NOT NULL,
    pome      DATE NOT NULL,
    borme     VARCHAR2(40) NOT NULL,
    tipme     VARCHAR2(40),
    zleb_idzl INTEGER NOT NULL
);

ALTER TABLE mec ADD CONSTRAINT mec_pk PRIMARY KEY ( idme,
                                                    zleb_idzl );

CREATE TABLE organizator (
    idk INTEGER NOT NULL
);

ALTER TABLE organizator ADD CONSTRAINT organizator_pk PRIMARY KEY ( idk );

CREATE TABLE prijava (
    takmicar_idk     INTEGER NOT NULL,
    kategorija_idkat INTEGER NOT NULL
);

ALTER TABLE prijava ADD CONSTRAINT prijava_pk PRIMARY KEY ( takmicar_idk,
                                                            kategorija_idkat );

CREATE TABLE rezultat (
    idrez          INTEGER NOT NULL,
    rez            INTEGER NOT NULL,
    ish            VARCHAR2(60) NOT NULL,
    je_na_mec_idme INTEGER NOT NULL,
    je_na_mec_idzl INTEGER NOT NULL,
    je_na_idk      INTEGER NOT NULL,
    je_na_idkat    INTEGER NOT NULL
);

ALTER TABLE rezultat ADD CONSTRAINT rezultat_pk PRIMARY KEY ( idrez );

CREATE TABLE sudi_na (
    sudija_idk       INTEGER NOT NULL,
    takmicenje_idtak INTEGER NOT NULL
);

ALTER TABLE sudi_na ADD CONSTRAINT sudi_na_pk PRIMARY KEY ( sudija_idk,
                                                            takmicenje_idtak );

CREATE TABLE sudija (
    idk   INTEGER NOT NULL,
    serts BLOB
);

ALTER TABLE sudija ADD CONSTRAINT sudija_pk PRIMARY KEY ( idk );

CREATE TABLE takmicar (
    idk       INTEGER NOT NULL,
    iskt      VARCHAR2(30),
    polt      CHAR(1) NOT NULL,
    datrot    DATE NOT NULL,
    klub_idkl INTEGER
);

ALTER TABLE takmicar ADD CONSTRAINT takmicar_pk PRIMARY KEY ( idk );

CREATE TABLE takmicenje (
    idtak           INTEGER NOT NULL,
    naztak          VARCHAR2(60) NOT NULL,
    dattak          DATE NOT NULL,
    bortak          VARCHAR2(60) NOT NULL,
    loktak          VARCHAR2(60) NOT NULL,
    organizator_idk INTEGER NOT NULL
);

ALTER TABLE takmicenje ADD CONSTRAINT takmicenje_pk PRIMARY KEY ( idtak );

CREATE TABLE trener (
    idk INTEGER NOT NULL
);

ALTER TABLE trener ADD CONSTRAINT trener_pk PRIMARY KEY ( idk );

CREATE TABLE zalba (
    takmicar_idk  INTEGER NOT NULL,
    takmicar_idk1 INTEGER NOT NULL
);

ALTER TABLE zalba ADD CONSTRAINT zalba_pk PRIMARY KEY ( takmicar_idk,
                                                        takmicar_idk1 );

CREATE TABLE zleb (
    idzl             INTEGER NOT NULL,
    brrun            INTEGER,
    brmec            INTEGER,
    tipzl            VARCHAR2(50) NOT NULL,
    kategorija_idkat INTEGER NOT NULL
);

ALTER TABLE zleb
    ADD CHECK ( tipzl IN ( 'Double-Elimination', 'Round-Robin', 'Single-Elimination' ) );

CREATE UNIQUE INDEX zleb__idx ON
    zleb (
        kategorija_idkat
    ASC );

ALTER TABLE zleb ADD CONSTRAINT zleb_pk PRIMARY KEY ( idzl );

ALTER TABLE je_na
    ADD CONSTRAINT je_na_mec_fk FOREIGN KEY ( mec_idme,
                                              mec_idzl )
        REFERENCES mec ( idme,
                         zleb_idzl );

ALTER TABLE je_na
    ADD CONSTRAINT je_na_prijava_fk FOREIGN KEY ( prijava_idk,
                                                  prijava_idkat )
        REFERENCES prijava ( takmicar_idk,
                             kategorija_idkat );

ALTER TABLE kategorija
    ADD CONSTRAINT kategorija_takmicenje_fk FOREIGN KEY ( takmicenje_idtak )
        REFERENCES takmicenje ( idtak );

ALTER TABLE klub
    ADD CONSTRAINT klub_trener_fk FOREIGN KEY ( trener_idk )
        REFERENCES trener ( idk );

ALTER TABLE mec
    ADD CONSTRAINT mec_zleb_fk FOREIGN KEY ( zleb_idzl )
        REFERENCES zleb ( idzl );

ALTER TABLE organizator
    ADD CONSTRAINT organizator_korisnik_fk FOREIGN KEY ( idk )
        REFERENCES korisnik ( idk );

ALTER TABLE prijava
    ADD CONSTRAINT prijava_kategorija_fk FOREIGN KEY ( kategorija_idkat )
        REFERENCES kategorija ( idkat );

ALTER TABLE prijava
    ADD CONSTRAINT prijava_takmicar_fk FOREIGN KEY ( takmicar_idk )
        REFERENCES takmicar ( idk );

ALTER TABLE rezultat
    ADD CONSTRAINT rezultat_je_na_fk FOREIGN KEY ( je_na_mec_idme,
                                                   je_na_mec_idzl,
                                                   je_na_idk,
                                                   je_na_idkat )
        REFERENCES je_na ( mec_idme,
                           mec_idzl,
                           prijava_idk,
                           prijava_idkat );

ALTER TABLE sudi_na
    ADD CONSTRAINT sudi_na_sudija_fk FOREIGN KEY ( sudija_idk )
        REFERENCES sudija ( idk );

ALTER TABLE sudi_na
    ADD CONSTRAINT sudi_na_takmicenje_fk FOREIGN KEY ( takmicenje_idtak )
        REFERENCES takmicenje ( idtak );

ALTER TABLE sudija
    ADD CONSTRAINT sudija_korisnik_fk FOREIGN KEY ( idk )
        REFERENCES korisnik ( idk );

ALTER TABLE takmicar
    ADD CONSTRAINT takmicar_klub_fk FOREIGN KEY ( klub_idkl )
        REFERENCES klub ( idkl );

ALTER TABLE takmicar
    ADD CONSTRAINT takmicar_korisnik_fk FOREIGN KEY ( idk )
        REFERENCES korisnik ( idk );

ALTER TABLE takmicenje
    ADD CONSTRAINT takmicenje_organizator_fk FOREIGN KEY ( organizator_idk )
        REFERENCES organizator ( idk );

ALTER TABLE trener
    ADD CONSTRAINT trener_korisnik_fk FOREIGN KEY ( idk )
        REFERENCES korisnik ( idk );

ALTER TABLE zalba
    ADD CONSTRAINT zalba_takmicar_fk FOREIGN KEY ( takmicar_idk )
        REFERENCES takmicar ( idk );

ALTER TABLE zalba
    ADD CONSTRAINT zalba_takmicar_fkv1 FOREIGN KEY ( takmicar_idk1 )
        REFERENCES takmicar ( idk );

ALTER TABLE zleb
    ADD CONSTRAINT zleb_kategorija_fk FOREIGN KEY ( kategorija_idkat )
        REFERENCES kategorija ( idkat );

CREATE OR REPLACE TRIGGER arc_fkarc_1_sudija BEFORE
    INSERT OR UPDATE OF idk ON sudija
    FOR EACH ROW
DECLARE
    d VARCHAR2(50);
BEGIN
    SELECT
        a.tipk
    INTO d
    FROM
        korisnik a
    WHERE
        a.idk = :new.idk;

    IF ( d IS NULL OR d <> 'Sudija' ) THEN
        raise_application_error(-20223, 'FK Sudija_Korisnik_FK in Table Sudija violates Arc constraint on Table Korisnik - discriminator column TipK doesn''t have value ''Sudija'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_organizator BEFORE
    INSERT OR UPDATE OF idk ON organizator
    FOR EACH ROW
DECLARE
    d VARCHAR2(50);
BEGIN
    SELECT
        a.tipk
    INTO d
    FROM
        korisnik a
    WHERE
        a.idk = :new.idk;

    IF ( d IS NULL OR d <> 'Organizator' ) THEN
        raise_application_error(-20223, 'FK Organizator_Korisnik_FK in Table Organizator violates Arc constraint on Table Korisnik - discriminator column TipK doesn''t have value ''Organizator'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_trener BEFORE
    INSERT OR UPDATE OF idk ON trener
    FOR EACH ROW
DECLARE
    d VARCHAR2(50);
BEGIN
    SELECT
        a.tipk
    INTO d
    FROM
        korisnik a
    WHERE
        a.idk = :new.idk;

    IF ( d IS NULL OR d <> 'Trener' ) THEN
        raise_application_error(-20223, 'FK Trener_Korisnik_FK in Table Trener violates Arc constraint on Table Korisnik - discriminator column TipK doesn''t have value ''Trener'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_1_takmicar BEFORE
    INSERT OR UPDATE OF idk ON takmicar
    FOR EACH ROW
DECLARE
    d VARCHAR2(50);
BEGIN
    SELECT
        a.tipk
    INTO d
    FROM
        korisnik a
    WHERE
        a.idk = :new.idk;

    IF ( d IS NULL OR d <> 'Takmicar' ) THEN
        raise_application_error(-20223, 'FK Takmicar_Korisnik_FK in Table Takmicar violates Arc constraint on Table Korisnik - discriminator column TipK doesn''t have value ''Takmicar'''
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             2
-- ALTER TABLE                             36
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           4
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
