-- Ukupan broj prijavljenih takmicara po gradovima
SELECT 
    TAKMICENJE.LOKTAK AS "Grad",
    COUNT(PRIJAVA.TAKMICAR_IDK) AS "Ukupan Broj Prijava"
FROM 
    TAKMICENJE
LEFT JOIN 
    KATEGORIJA ON TAKMICENJE.IDTAK = KATEGORIJA.TAKMICENJE_IDTAK
LEFT JOIN 
    PRIJAVA ON KATEGORIJA.IDKAT = PRIJAVA.KATEGORIJA_IDKAT
LEFT JOIN 
    TAKMICAR ON PRIJAVA.TAKMICAR_IDK = TAKMICAR.IDK
GROUP BY 
    TAKMICENJE.LOKTAK
ORDER BY 
    "Ukupan Broj Prijava" DESC;

-- Sva takmicenja sa brojem prijava po kategoriji
SELECT 
    TK.NAZTAK AS "Naziv Takmi?enja",
    K.NAZKAT AS "Naziv Kategorije",
    COUNT(P.TAKMICAR_IDK) AS "Broj Prijava"
FROM 
    TAKMICENJE TK
JOIN 
    KATEGORIJA K ON TK.IDTAK = K.TAKMICENJE_IDTAK
LEFT JOIN 
    PRIJAVA P ON K.IDKAT = P.KATEGORIJA_IDKAT
LEFT JOIN 
    TAKMICAR T ON P.TAKMICAR_IDK = T.IDK
GROUP BY 
    TK.NAZTAK, K.NAZKAT
ORDER BY 
    "Broj Prijava" DESC;

-- Broj muskih takmicara rodjenije posle 1990 godine, po takmicenjima    
    
SELECT 
    TAKMICENJE.IDTAK AS "ID Takmi?enja",
    TAKMICENJE.NAZTAK AS "Naziv Takmi?enja",
    COUNT(TAKMICAR.IDK) AS "Broj Muških Takmi?ara"
FROM 
    TAKMICENJE
LEFT JOIN 
    KATEGORIJA ON TAKMICENJE.IDTAK = KATEGORIJA.TAKMICENJE_IDTAK
LEFT JOIN 
    PRIJAVA ON KATEGORIJA.IDKAT = PRIJAVA.KATEGORIJA_IDKAT
LEFT JOIN 
    TAKMICAR ON PRIJAVA.TAKMICAR_IDK = TAKMICAR.IDK
WHERE 
    TAKMICAR.POLT = 'M' AND EXTRACT(YEAR FROM TAKMICAR.DATROT) > 1990
GROUP BY 
    TAKMICENJE.IDTAK, TAKMICENJE.NAZTAK
ORDER BY 
    "Broj Muških Takmi?ara" DESC;
    

    
